/**
 * Fudgio site builder.
 *
 *     node scripts/build.mjs
 *
 * Writes every storefront page, robots.txt, sitemap.xml and assets/catalog.js
 * from one place, so the header, footer, SEO tags and prices cannot drift
 * apart page by page. The catalogue comes from api/catalog.php (via php -r),
 * which is also what seeds the database, and the cards and product pages are
 * drawn by the same functions in assets/store.js the browser uses — run here
 * in a sandbox — so the static HTML and the live page are identical.
 *
 * Run it after changing copy, the catalogue, store.css or any assets/*.js.
 * Only facts we can stand behind go into the structured data: no invented
 * ratings, review counts or addresses.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import vm from 'node:vm';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const SITE = 'https://fudgio.com';
const BRAND = 'Fudgio';
const OG = SITE + '/assets/og-image.png';
const r = (f) => readFileSync(path.join(ROOT, f), 'utf8');
const w = (f, s) => { mkdirSync(path.dirname(path.join(ROOT, f)), { recursive: true }); writeFileSync(path.join(ROOT, f), s); };

/* ---------------- data from PHP ---------------- */
const data = JSON.parse(execFileSync('php', ['-r', `
  require ${JSON.stringify(ROOT + '/api/db.php')};
  echo json_encode([
    'catalog' => array_map(fn($b) => array_intersect_key($b, array_flip(['slug','name','color','ink','tagline','description','sort','sizes','details'])), bandana_catalog()),
    'defaults' => [
      'deliveryFee' => (int) env('DELIVERY_FEE', '250'), 'freeOver' => (int) env('FREE_DELIVERY_OVER', '8000'),
      'intlShipping' => (int) env('INTL_SHIPPING_USD', '12'), 'intlFreeOver' => (int) env('INTL_FREE_OVER_USD', '0'),
      'usdRate' => (int) env('USD_RATE', '280'), 'bundleQty' => (int) env('BUNDLE_QTY', '3'), 'bundlePct' => (int) env('BUNDLE_PCT', '15'),
      'daysPk' => (string) env('DELIVERY_DAYS_PK', '3–5'), 'daysIntl' => (string) env('DELIVERY_DAYS_INTL', '7–14'),
      'email' => (string) env('PUBLIC_EMAIL', 'faaz.saleem@fudgio.com'),
    ],
  ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);`], { encoding: 'utf8' }));
const CAT = data.catalog, D = data.defaults;

w('assets/catalog.js', '/* Generated by scripts/build.mjs from api/catalog.php and .env — do not edit. */\n'
  + 'var FUDGIO_CATALOG = ' + JSON.stringify(CAT) + ';\n'
  + 'var FUDGIO_DEFAULTS = ' + JSON.stringify(D) + ';\n');

/* ---------------- the browser's own templates, run here ---------------- */
const ctx = vm.createContext({ console, FUDGIO_FORCE_REGION: 'PK' });
for (const f of ['assets/art.js', 'assets/catalog.js', 'assets/store.js']) vm.runInContext(r(f), ctx, { filename: f });
const S = ctx;
const P = S.visibleProducts();
const ONE = P[0].sizes[0];
const rs = (n) => 'Rs ' + Number(n).toLocaleString('en-US');

/* ---------------- asset versions ---------------- */
const ver = (f) => createHash('sha256').update(r(f)).digest('hex').slice(0, 8);
const V = {};
for (const f of ['assets/store.css', 'assets/art.js', 'assets/catalog.js', 'assets/store.js', 'assets/cart.js', 'assets/checkout.js', 'assets/track.js', 'assets/forms.js'])
  if (existsSync(path.join(ROOT, f))) V[f] = ver(f);
const src = (f) => `/${f}?v=${V[f] || '0'}`;

const e = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const ARROW = '<svg class="arrow" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>';
const mark = S.bandanaSVG('#FF6A13', '#FFFFFF');

/* ---------------- shared layout ---------------- */
function head(m) {
  const canonical = SITE + m.url;
  const robots = m.index ? 'index, follow, max-image-preview:large' : 'noindex, follow';
  const ld = (m.ld || []).map((x) => '<script type="application/ld+json">' + JSON.stringify({ '@context': 'https://schema.org', ...x }) + '</script>').join('\n');
  const fonts = 'https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800&family=DM+Mono:wght@400;500&display=swap';
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<!-- Generated by scripts/build.mjs — edit that file, not this page. -->
<title>${e(m.title)}</title>
<meta name="description" content="${e(m.desc)}"/>
<link rel="canonical" href="${canonical}"/>
<meta name="robots" content="${robots}"/>
<link rel="icon" href="/favicon.ico" sizes="32x32"/>
<link rel="icon" type="image/png" sizes="48x48" href="/assets/favicon-48.png"/>
<link rel="icon" type="image/png" sizes="96x96" href="/assets/favicon-96.png"/>
<link rel="icon" type="image/png" sizes="192x192" href="/assets/favicon-192.png"/>
<link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png"/>
<link rel="manifest" href="/site.webmanifest"/>
<meta name="theme-color" content="#0d0d0d"/>
<meta property="og:type" content="${m.ogType || 'website'}"/>
<meta property="og:site_name" content="${BRAND}"/>
<meta property="og:title" content="${e(m.title)}"/>
<meta property="og:description" content="${e(m.desc)}"/>
<meta property="og:url" content="${canonical}"/>
<meta property="og:image" content="${OG}"/>
<meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>
<meta property="og:image:alt" content="Fudgio printed cotton bandanas in eight colours"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content="${e(m.title)}"/>
<meta name="twitter:description" content="${e(m.desc)}"/>
<meta name="twitter:image" content="${OG}"/>
${ld}
<link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link rel="preload" as="style" href="${fonts}" onload="this.onload=null;this.rel='stylesheet'"/>
<noscript><link rel="stylesheet" href="${fonts}"/></noscript>
<link rel="stylesheet" href="${src('assets/store.css')}"/>
</head>`;
}

function header() {
  return `<a class="skip" href="#main">Skip to content</a>
<div class="announce" id="announce">Free delivery in Pakistan over ${rs(D.freeOver)} · Cash on delivery · Buy any ${D.bundleQty}, save ${D.bundlePct}%</div>
<header class="site-header"><div class="wrap nav">
  <a href="/" class="brand" aria-label="Fudgio home"><span class="brand-mark" aria-hidden="true">${mark}</span>FUDGIO</a>
  <div class="nav-right">
    <nav class="nav-links" id="navLinks" aria-label="Main">
      <a class="nav-link" href="/shop">Shop</a>
      <a class="nav-link" href="/how-to-wear">How to wear</a>
      <a class="nav-link" href="/#bundle">Bundle deal</a>
      <a class="nav-link m-only m-gap" href="/track">Track your order</a>
      <a class="nav-link m-only" href="/shipping">Delivery &amp; returns</a>
      <a class="nav-link m-only" href="/faq">FAQ</a>
      <a class="nav-link m-only" href="/contact">Contact</a>
    </nav>
    <div class="nav-tools">
      <button type="button" class="cur-btn" id="curBtn">PKR ₨</button>
      <a href="/cart" class="bag-btn" id="bagBtn" aria-label="Your bag"><span class="bag-word">Bag</span><span class="bag-count" id="cartCount">0</span></a>
      <button type="button" class="menu-btn" id="menuBtn" aria-label="Menu" aria-expanded="false" aria-controls="navLinks"><span></span></button>
    </div>
  </div>
</div></header>`;
}

function footer() {
  return `<footer class="site-footer dark"><div class="wrap">
  <div class="news">
    <div class="stack"><h2>Get new colours first.</h2><p>Leave your email and we’ll tell you when the next drop is live.</p></div>
    <form class="news-form" data-news novalidate>
      <label for="newsEmail">Email address</label>
      <div class="news-row"><input id="newsEmail" type="email" name="email" autocomplete="email" placeholder="you@email.com" required/>
        <input class="hp" type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true"/>
        <button type="submit" class="btn btn-light">Notify me</button></div>
      <div class="news-msg" role="status" aria-live="polite"></div>
    </form>
  </div>
  <div class="foot-row">
    <a href="/" class="brand">FUDGIO</a>
    <nav class="foot-links" aria-label="Footer">
      <a href="/shop">Shop</a><a href="/how-to-wear">How to wear</a><a href="/#bundle">Bundle deal</a>
      <a data-ig hidden href="#" rel="noopener" target="_blank">Instagram</a><a data-wa hidden href="#" rel="noopener" target="_blank">WhatsApp</a>
      <a href="/shipping">Delivery &amp; returns</a>
    </nav>
  </div>
  <div class="foot-small">
    <span>© <span id="yr">2026</span> Fudgio · Cash on delivery in Pakistan · Shipping worldwide</span>
    <nav aria-label="Help"><a href="/track">Track your order</a><a href="/faq">FAQ</a><a href="/care">Size &amp; care</a><a href="/bulk-orders">Bulk &amp; custom</a><a href="/about">About</a><a href="/contact">Contact</a></nav>
  </div>
</div></footer>`;
}

function page(m, body, scripts = []) {
  const js = ['assets/art.js', 'assets/catalog.js', 'assets/store.js', ...scripts].map((f) => `<script src="${src(f)}"></script>`).join('\n');
  return `${head(m)}
<body${m.bodyClass ? ` class="${m.bodyClass}"` : ''}>
${header()}
<main id="main">
${body}
</main>
${footer()}
${js}
</body>
</html>
`;
}

/* ---------------- sections ---------------- */
const marquee = () => {
  const words = ['Head', 'Neck', 'Wrist', 'Bag', 'Pocket', 'Head', 'Neck', 'Wrist', 'Bag', 'Pocket'];
  const run = words.map((x) => `<span>${x}</span><span class="sl">/</span>`).join('');
  return `<div class="marquee" aria-hidden="true"><div class="track"><div class="run">${run}</div><div class="run">${run}</div></div></div>`;
};
const grid = (opts = {}) => {
  const list = P.filter((p) => p.slug !== opts.exclude).slice(0, opts.limit || 99);
  return `<div class="grid" data-grid${opts.exclude ? ` data-exclude="${opts.exclude}"` : ''}${opts.limit ? ` data-limit="${opts.limit}"` : ''}>${list.map((p) => S.productCardHTML(p)).join('')}</div>`;
};
const full = ONE.price * D.bundleQty, off = Math.round(full * D.bundlePct / 100);
const band = () => `<section id="bundle" class="orange" aria-labelledby="bundleTitle"><div class="wrap band">
  <div class="stack">
    <p class="eyebrow">Bundle deal</p>
    <h2 id="bundleTitle">Buy any <span data-qty>${D.bundleQty}</span>, save <span data-pct>${D.bundlePct}</span>%.</h2>
    <p>Mix any three colours. The discount is applied automatically at checkout.</p>
    <p class="sum" data-bundle-sum>${D.bundleQty} × ${rs(ONE.price)} = <s>${rs(full)}</s> ${rs(full - off)}</p>
  </div>
  <div class="band-side"><div class="trio" data-trio aria-hidden="true"></div><a href="/shop" class="btn btn-dark">Pick your three ${ARROW}</a></div>
</div></section>`;
const WAYS = [
  ['Head', 'Fold it into a triangle and tie it at the back of your head.',
    ['Lay it flat and fold corner to corner into a triangle.', 'Put the long edge across your forehead, point to the back.', 'Tie the two ends over the point at the nape of your neck.']],
  ['Neck', 'Tie a loose knot at the front. It lifts a plain t-shirt straight away.',
    ['Fold into a triangle, then roll from the long edge to a 5 cm band.', 'Wrap it round your neck, ends to the front.', 'Tie a loose knot off to one side.']],
  ['Wrist', 'Roll it thin, wrap it twice and tuck in the ends.',
    ['Fold into a triangle and roll tightly into a thin cord.', 'Wrap twice round your wrist.', 'Tie a small knot and tuck the ends underneath.']],
  ['Bag', 'Knot it around the strap or handle to add colour to any bag.',
    ['Fold into a triangle and roll to a band.', 'Loop it round the base of the handle.', 'Tie a bow or a single knot and let the ends hang.']],
  ['Back pocket', 'Let one corner hang out of your back pocket.',
    ['Fold in half, then in half again.', 'Tuck the folded square into a back pocket.', 'Pull one corner out so the print shows.']],
];
const wear = (detailed = false) => `<section id="wear" class="dark" aria-labelledby="wearTitle"><div class="wrap sec wear">
  <div class="wear-intro"><p class="eyebrow">How to wear</p><h2 class="h2" id="wearTitle">One bandana,<br>five ways.</h2>
    <p>Not sure how to style it? Start with one of these.</p>${detailed ? '' : '<p><a class="link" href="/how-to-wear">Step-by-step guide</a></p>'}</div>
  <ol class="ways">${WAYS.map(([h, p, steps], i) => `<li class="way"><span class="n">0${i + 1}</span><h3>${h}</h3><p>${p}</p>${detailed ? `<ol>${steps.map((s) => `<li>${s}</li>`).join('')}</ol>` : ''}</li>`).join('')}</ol>
</div></section>`;
const perks = () => `<div class="perks">
  <div class="perk"><span class="k">Pakistan</span><b>Cash on delivery</b><p>Pay the rider when it arrives. Free delivery over ${rs(D.freeOver)}.</p></div>
  <div class="perk"><span class="k">Worldwide</span><b>$${D.intlShipping} flat shipping</b><p>To any country, tracked, in <span data-days-intl>${D.daysIntl}</span> working days.</p></div>
  <div class="perk"><span class="k">Fabric</span><b>100% cotton</b><p>Soft from the first wear, with hemmed edges that don’t fray.</p></div>
  <div class="perk"><span class="k">Easy</span><b>7-day exchanges</b><p>Wrong colour? Swap it while it’s unworn and unwashed.</p></div>
</div>`;
const pageHead = (eyebrow, title, lede, crumbs) => `<section class="dark"><div class="wrap page-head">
  ${crumbs ? `<nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a><span class="sep">/</span><span>${crumbs}</span></nav>` : ''}
  <p class="eyebrow">${eyebrow}</p><h1 class="h1">${title}</h1>${lede ? `<p class="lede">${lede}</p>` : ''}
</div></section>`;

/* ---------------- structured data ---------------- */
const org = { '@type': 'OnlineStore', '@id': SITE + '/#store', name: BRAND, url: SITE, logo: SITE + '/assets/icon-512.png', image: OG,
  description: 'Printed 100% cotton bandanas in eight colours. Cash on delivery across Pakistan, shipped worldwide.',
  email: D.email, currenciesAccepted: 'PKR, USD', paymentAccepted: 'Cash on delivery (Pakistan), online payment link (international)',
  areaServed: 'Worldwide' };
const crumbs = (trail) => ({ '@type': 'BreadcrumbList', itemListElement: trail.map(([n, u], i) => ({ '@type': 'ListItem', position: i + 1, name: n, item: SITE + u })) });
const productLd = (p) => ({ '@type': 'Product', name: p.name + ' bandana', description: p.desc, image: OG, url: SITE + p.path, sku: 'FUD-' + p.slug,
  brand: { '@type': 'Brand', name: BRAND }, category: 'Apparel & Accessories > Clothing Accessories > Bandanas', color: p.name, material: 'Cotton',
  size: '55 × 55 cm',
  offers: [
    { '@type': 'Offer', price: String(p.sizes[0].price), priceCurrency: 'PKR', availability: 'https://schema.org/InStock', url: SITE + p.path, eligibleRegion: { '@type': 'Country', name: 'PK' } },
    { '@type': 'Offer', price: String(p.sizes[0].usd), priceCurrency: 'USD', availability: 'https://schema.org/InStock', url: SITE + p.path },
  ] });

const FAQ = [
  ['Ordering', [
    ['How does the bundle deal work?', `Put any ${D.bundleQty} or more bandanas in your bag, in any mix of colours, and ${D.bundlePct}% comes off the bandanas automatically. You see the discount in your bag before you check out.`],
    ['Do I need an account?', 'No. Fill in your delivery details at checkout and you are done. You get an order number to track it with.'],
    ['Can I change or cancel my order?', 'Yes, until it ships. Message us with your order number as soon as you can and we will sort it out.'],
  ]],
  ['Delivery', [
    ['Do you ship outside Pakistan?', `Yes, to every country we can reach by tracked courier. International shipping is a flat $${D.intlShipping} and takes about ${D.daysIntl} working days.`],
    ['How long does delivery take in Pakistan?', `Usually ${D.daysPk} working days to any city in Pakistan. Delivery is ${rs(D.deliveryFee)}, and free on orders over ${rs(D.freeOver)}.`],
    ['How do I track my order?', 'Use the order number from checkout (like FUD-1001) with your phone number on the Track your order page.'],
  ]],
  ['Payment', [
    ['How do I pay in Pakistan?', 'Cash on delivery. You pay the rider in cash when your bandanas arrive; nothing is paid online.'],
    ['How do I pay from abroad?', 'International orders are paid before they ship. After you order we send a secure payment link, and your bandanas are packed as soon as it is paid. Prices are in US dollars.'],
    ['Why do you text me a code at checkout?', 'In Pakistan we confirm cash-on-delivery orders with a code sent to your mobile, so riders are not sent to fake orders. It takes a few seconds.'],
  ]],
  ['Product', [
    ['What size are the bandanas?', 'Every bandana is a 55 × 55 cm (22") square, the classic size that ties round your head, neck or wrist.'],
    ['What are they made of?', '100% cotton with hemmed edges and a colourfast print.'],
    ['How do I wash it?', 'Machine wash cold with similar colours, or hand wash. Line dry. Wash it alone the first time, as cotton can release a little colour.'],
    ['What if I want to return it?', 'Unworn and unwashed bandanas can be exchanged within 7 days of delivery. Faulty items are always replaced. See Delivery & returns for how.'],
  ]],
];

/* ---------------- pages ---------------- */
const pages = [];
const add = (file, m, body, scripts) => pages.push({ file, m, html: page(m, body, scripts) });

// Home
const hero = `<section class="dark"><div class="wrap"><div class="hero">
  <div class="hero-copy">
    <p class="eyebrow fade">Printed bandanas / ${P.length} colours</p>
    <h1 class="h1 hero-title"><span class="line"><span>The bandana</span></span><span class="line"><span>that finishes</span></span><span class="line"><span>the fit.</span></span></h1>
    <p class="lede fade d2">Square printed bandanas in eight colours. Wear one on your head, around your neck, on your wrist or tied to your bag.</p>
    <div class="hero-cta fade d3"><a href="#shop" class="btn btn-primary">Shop all ${P.length} colours ${ARROW}</a><span class="hero-from" data-from>From ${rs(ONE.price)}</span></div>
    <div class="hero-specs fade d4"><span>55 cm square</span><span>100% cotton</span><span>Delivered in <span data-days>${D.daysPk}</span> days</span></div>
  </div>
  <div class="hero-art fade d1">
    <div class="float f1"><div class="bn">${S.bandanaSVG('#1D2B5C', '#EFECE6')}</div></div>
    <div class="float f2"><div class="bn">${S.bandanaSVG('#D9A21B', '#141414')}</div></div>
    <div class="float f3"><div class="bn">${S.bandanaSVG('#C3201B', '#F3EDE0')}</div></div>
    <a class="sticker" href="#bundle" data-sticker-wrap aria-label="Buy any ${D.bundleQty}, save ${D.bundlePct} percent">
      <svg viewBox="0 0 132 132" aria-hidden="true"><path id="stickerPath" d="M66 66m-50 0a50 50 0 1 1 100 0a50 50 0 1 1-100 0" fill="none"/><text><textPath href="#stickerPath" data-sticker>Buy any ${D.bundleQty} · save ${D.bundlePct}% · Buy any ${D.bundleQty} · save ${D.bundlePct}% · </textPath></text></svg>
      <b><span data-pct>${D.bundlePct}</span>%<small>off ${D.bundleQty}+</small></b>
    </a>
  </div>
</div></div></section>`;
const shopSection = (h = 'h2') => `<section id="shop" class="paper" aria-labelledby="shopTitle"><div class="wrap sec">
  <div class="sec-head"><div class="stack"><p class="eyebrow">Shop</p><${h} class="h2" id="shopTitle">Choose your colour</${h}></div>
    <p>Same size and print on every one. Tap a colour to add it to your bag.</p></div>
  <div class="deal-meter" data-deal-meter hidden></div>
  ${grid()}
  ${perks()}
</div></section>`;
add('index.html', {
  url: '/', index: true, priority: '1.0',
  title: 'Fudgio — Printed Cotton Bandanas in 8 Colours · Shipped Worldwide',
  desc: `Square printed bandanas in eight colours, 100% cotton, 55 cm. Buy any ${D.bundleQty}, save ${D.bundlePct}%. Cash on delivery across Pakistan and shipping worldwide.`,
  ld: [org, { '@type': 'WebSite', '@id': SITE + '/#website', url: SITE, name: BRAND, publisher: { '@id': SITE + '/#store' }, inLanguage: 'en' }],
}, hero + marquee() + shopSection() + wear() + band());

// Shop
add('shop.html', {
  url: '/shop', index: true, priority: '0.9',
  title: 'Shop Bandanas — One Print in 8 Colours | Fudgio',
  desc: `All eight Fudgio bandanas: Classic Red, Jet Black, Navy, Forest Green, Mustard, Bone, Plum and Rust. 100% cotton, 55 cm square, from ${rs(ONE.price)} or $${ONE.usd}. Buy any ${D.bundleQty}, save ${D.bundlePct}%.`,
  ld: [{ '@type': 'ItemList', name: 'Fudgio bandanas', itemListElement: P.map((p, i) => ({ '@type': 'ListItem', position: i + 1, name: p.name + ' bandana', url: SITE + p.path })) }, crumbs([['Home', '/'], ['Shop', '/shop']])],
}, pageHead('Shop / ' + P.length + ' colours', 'Every colour,<br>one great print.', `100% cotton, 55 cm square, hemmed edges. <span data-from>From ${rs(ONE.price)}</span> — and any ${D.bundleQty} take ${D.bundlePct}% off.`, 'Shop')
  + `<section class="paper"><div class="wrap sec"><div class="deal-meter" data-deal-meter hidden></div>${grid()}${perks()}</div></section>` + band() + wear());

// Product pages
const productExtras = (slug) => `<section class="paper" aria-labelledby="moreTitle"><div class="wrap sec">
  <div class="sec-head"><div class="stack"><p class="eyebrow">Make it three</p><h2 class="h2" id="moreTitle">Pick your other two</h2></div>
    <p>Any ${D.bundleQty} colours take <span data-pct>${D.bundlePct}</span>% off, worked out in your bag.</p></div>
  ${grid({ exclude: slug, limit: 4 })}
  <p style="margin-top:36px"><a class="link" href="/shop">See all ${P.length} colours</a></p>
</div></section>` + wear() + band();
for (const p of P) {
  add(`bandanas/${p.slug}.html`, {
    url: p.path, index: true, priority: '0.8', ogType: 'product',
    title: `${p.name} Bandana — 100% Cotton, 55 cm | Fudgio`,
    desc: `${p.desc} ${rs(p.sizes[0].price)} with cash on delivery in Pakistan, or $${p.sizes[0].usd} shipped worldwide.`,
    ld: [productLd(p), crumbs([['Home', '/'], ['Shop', '/shop'], [p.name, p.path]])],
  }, `<section class="dark"><div class="wrap" data-pd-root="${p.slug}">${S.productPageHTML(p)}</div></section>` + productExtras(p.slug));
}
// Any colour added in the admin after the last build
add('bandana.html', { url: '/bandana', index: false, title: 'Bandana | Fudgio', desc: 'A Fudgio printed cotton bandana.' },
  `<section class="dark"><div class="wrap" data-pd-root=""><div class="empty" style="padding:120px 0"><p class="eyebrow">Loading…</p></div></div></section>` + productExtras(''));

// How to wear
add('how-to-wear.html', {
  url: '/how-to-wear', index: true, priority: '0.7',
  title: 'How to Wear a Bandana — 5 Easy Ways | Fudgio',
  desc: 'Five ways to wear a bandana, step by step: on your head, round your neck, on your wrist, tied to a bag, or hanging from a back pocket.',
  ld: [crumbs([['Home', '/'], ['How to wear', '/how-to-wear']]), { '@type': 'HowTo', name: 'How to wear a bandana on your head', step: WAYS[0][2].map((t, i) => ({ '@type': 'HowToStep', position: i + 1, text: t })) }],
}, pageHead('How to wear', 'Five ways<br>to wear it.', 'Every one starts the same way: lay it flat, fold it corner to corner. Here is what to do next.', 'How to wear')
  + wear(true).replace('<section id="wear" class="dark"', '<section class="dark rule-top"')
  + `<section class="paper"><div class="wrap sec"><div class="sec-head"><div class="stack"><p class="eyebrow">Now pick one</p><h2 class="h2">Choose your colour</h2></div><p>Same size and print on every one.</p></div>${grid({ limit: 4 })}<p style="margin-top:36px"><a class="link" href="/shop">See all ${P.length} colours</a></p></div></section>` + band());

// Delivery & returns
add('shipping.html', {
  url: '/shipping', index: true, priority: '0.6',
  title: 'Delivery & Returns — Cash on Delivery in Pakistan, Shipping Worldwide | Fudgio',
  desc: `Fudgio delivers across Pakistan with cash on delivery (${rs(D.deliveryFee)}, free over ${rs(D.freeOver)}) and ships worldwide for $${D.intlShipping} flat. 7-day exchanges on unworn bandanas.`,
  ld: [crumbs([['Home', '/'], ['Delivery & returns', '/shipping']])],
}, pageHead('Delivery & returns', 'Wherever you are,<br>it gets to you.', 'Cash on delivery across Pakistan. Tracked shipping to the rest of the world.', 'Delivery &amp; returns')
  + `<section class="paper"><div class="wrap sec">
  <div class="cols">
    <div class="box reveal-me"><p class="eyebrow">Pakistan</p><h3>Cash on delivery</h3>
      <dl class="kv"><dt>Cost</dt><dd><span data-s="deliveryFee">${rs(D.deliveryFee)}</span> · free over <span data-s="freeOver">${rs(D.freeOver)}</span></dd>
      <dt>Time</dt><dd><span data-days-pk>${D.daysPk}</span> working days, every city</dd><dt>Pay</dt><dd>Cash to the rider when it arrives</dd>
      <dt>Confirm</dt><dd>We text a code to your mobile at checkout</dd></dl></div>
    <div class="box reveal-me"><p class="eyebrow">Worldwide</p><h3>Tracked shipping</h3>
      <dl class="kv"><dt>Cost</dt><dd><span data-s="intlShipping">$${D.intlShipping}</span> flat, any number of bandanas</dd>
      <dt>Time</dt><dd><span data-days-intl>${D.daysIntl}</span> working days</dd><dt>Pay</dt><dd>Secure payment link, before it ships</dd>
      <dt>Duties</dt><dd>Any import duties or taxes are set by your country and paid on arrival</dd></dl></div>
  </div>
  <div class="prose" style="margin-top:64px">
    <h2>Exchanges and returns</h2>
    <p>Changed your mind about the colour? You can exchange any bandana that is <strong>unworn, unwashed and still folded</strong> within <strong>7 days</strong> of delivery.</p>
    <ol><li>Message us with your order number and the colour you want instead.</li><li>Send the bandana back to the address we give you.</li><li>We send the new colour as soon as it arrives. In Pakistan, the second delivery is on us.</li></ol>
    <p>Something wrong with it — a flaw in the print or the stitching, or the wrong colour sent? We replace it, free, wherever you are. Send a photo and your order number.</p>
    <h2>Tracking</h2>
    <p>Every order gets a number at checkout, like FUD-1001. <a href="/track">Track your order</a> with it and your phone number.</p>
  </div>
</div></section>`);

// Size & care
add('care.html', {
  url: '/care', index: true, priority: '0.5',
  title: 'Bandana Size & Care Guide — 55 cm, 100% Cotton | Fudgio',
  desc: 'Every Fudgio bandana is a 55 × 55 cm square of 100% cotton. How it fits, how to wash it and how to keep the colour bright.',
  ld: [crumbs([['Home', '/'], ['Size & care', '/care']])],
}, pageHead('Size &amp; care', 'One size.<br>Fits every way.', 'A 55 cm square is the classic bandana size: big enough for your head, small enough for your wrist.', 'Size &amp; care')
  + `<section class="paper"><div class="wrap sec"><div class="cols">
  <div class="box reveal-me"><p class="eyebrow">The size</p><div class="big">55 × 55 cm</div><p>22 × 22 inches. Folded into a triangle, the long edge is about 78 cm — enough to tie round most heads with ends to spare.</p></div>
  <div class="box reveal-me"><p class="eyebrow">The fabric</p><div class="big">100% cotton</div><p>Light, breathable and soft from the first wear. Hemmed edges so it doesn’t fray.</p></div>
  <div class="box reveal-me"><p class="eyebrow">The print</p><div class="big">Colourfast</div><p>The same print on all eight colours, made to last through washes.</p></div>
</div>
<div class="prose" style="margin-top:64px">
  <h2>Washing</h2>
  <ul><li>Machine wash cold (30°C) with similar colours, or hand wash.</li><li>Wash it on its own the first time — new cotton can release a little colour.</li><li>Line dry out of strong sun. Don’t tumble dry.</li><li>Iron warm on the reverse.</li><li>No bleach.</li></ul>
  <h2>Folding it to wear</h2>
  <p>Almost every way to wear a bandana starts by folding it corner to corner into a triangle. For a neck or wrist band, roll it from the long edge. <a href="/how-to-wear">See all five ways</a>.</p>
</div></div></section>`);

// About
add('about.html', {
  url: '/about', index: true, priority: '0.5',
  title: 'About Fudgio — Printed Bandanas from Pakistan',
  desc: 'Fudgio makes one printed bandana in eight colours, sold with cash on delivery across Pakistan and shipped worldwide.',
  ld: [crumbs([['Home', '/'], ['About', '/about']])],
}, pageHead('About', 'One print.<br>Eight colours.<br>No fuss.', '', 'About')
  + `<section class="paper"><div class="wrap sec"><div class="prose">
  <p style="font-size:1.375rem;color:var(--text);font-weight:500;letter-spacing:-.01em">A bandana is the cheapest way to change an outfit. Fudgio makes one good one, in eight colours, and gets it to you wherever you are.</p>
  <h2>Why one print</h2>
  <p>Instead of a hundred designs, we picked a single classic print — a centre medallion, corner fans and a fine dotted field — and made it in eight colours that go with what people actually wear. Same size, same quality, every time. Pick the colour; that’s the whole decision.</p>
  <h2>How we sell</h2>
  <p>In Pakistan you pay cash when it arrives, so there is nothing to risk. Everywhere else, you pay by a secure link before it ships, at one flat shipping price. And because bandanas are better in threes, any three take ${D.bundlePct}% off.</p>
  <h2>Talk to us</h2>
  <p>Questions, a custom order for your team, or just to say hi — <a href="/contact">get in touch</a>.</p>
</div></div></section>` + band());

// FAQ
add('faq.html', {
  url: '/faq', index: true, priority: '0.6',
  title: 'FAQ — Bundle Deal, Delivery, Payment & Returns | Fudgio',
  desc: 'Answers about the buy-3 bundle deal, delivery in Pakistan and worldwide, cash on delivery, paying from abroad, sizes, washing and exchanges.',
  ld: [{ '@type': 'FAQPage', mainEntity: FAQ.flatMap(([, qs]) => qs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } }))) }, crumbs([['Home', '/'], ['FAQ', '/faq']])],
}, pageHead('FAQ', 'Questions,<br>answered.', 'Can’t find yours? <a class="link" href="/contact">Ask us</a>.', 'FAQ')
  + `<section class="paper"><div class="wrap sec" style="max-width:920px">${FAQ.map(([g, qs]) => `<div class="faq-group"><h2>${g}</h2><div class="faq">${qs.map(([q, a]) => `<details><summary>${e(q)}</summary><div class="a"><p>${e(a)}</p></div></details>`).join('')}</div></div>`).join('')}</div></section>`);

// Contact + bulk
const contactForm = (topic, extra = '') => `<form class="form panel" data-contact data-topic="${topic}" novalidate>
  <div class="row2"><div class="field"><label for="cName">Name</label><input id="cName" name="name" autocomplete="name" required/></div>
  <div class="field"><label for="cEmail">Email</label><input id="cEmail" name="email" type="email" autocomplete="email" required/></div></div>
  <div class="row2"><div class="field"><label for="cPhone">Phone / WhatsApp (optional)</label><input id="cPhone" name="phone" type="tel" autocomplete="tel"/></div>
  <div class="field"><label for="cTopic">About</label><select id="cTopic" name="topic">${['Order', 'Bulk or custom', 'Wholesale', 'Press', 'Other'].map((t) => `<option${t === topic ? ' selected' : ''}>${t}</option>`).join('')}</select></div></div>
  ${extra}
  <div class="field"><label for="cMsg">Message</label><textarea id="cMsg" name="message" required></textarea></div>
  <input class="hp" type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true"/>
  <div class="err" data-err role="alert"></div>
  <button type="submit" class="btn btn-primary">Send message ${ARROW}</button>
</form>`;
add('contact.html', {
  url: '/contact', index: true, priority: '0.5',
  title: 'Contact Fudgio — Orders, Bulk & Custom Bandanas',
  desc: 'Get in touch with Fudgio about an order, a bulk or custom bandana order, or wholesale. We reply within a day.',
  ld: [crumbs([['Home', '/'], ['Contact', '/contact']])],
}, pageHead('Contact', 'Say hello.', 'About an order, a bulk run for your team, or anything else. We reply within a day.', 'Contact')
  + `<section class="paper"><div class="wrap sec"><div class="split">${contactForm('Order')}
  <div class="form">
    <div class="box"><p class="eyebrow">Email</p><a class="link" style="font-size:1.125rem" href="mailto:${D.email}">${D.email}</a></div>
    <div class="box" data-wa-box><p class="eyebrow">WhatsApp</p><a class="link" data-wa hidden href="#" target="_blank" rel="noopener">Message us on WhatsApp</a><p class="muted" style="font-size:.95rem">Quickest for order questions in Pakistan.</p></div>
    <div class="box"><p class="eyebrow">Instagram</p><a class="link" data-ig data-ig-handle hidden href="#" target="_blank" rel="noopener">Instagram</a><p class="muted" style="font-size:.95rem">New colours land there first.</p></div>
    <div class="box"><p class="eyebrow">Your order</p><p>Have an order number? <a class="link" href="/track">Track it here</a>.</p></div>
  </div></div></div></section>`, ['assets/forms.js']);
add('bulk-orders.html', {
  url: '/bulk-orders', index: true, priority: '0.6',
  title: 'Bulk & Custom Bandanas for Teams, Events and Brands | Fudgio',
  desc: 'Bandanas in bulk for teams, events, schools, weddings and brands. Mix any of our eight colours from 20 pieces, or ask about custom colours and prints.',
  ld: [crumbs([['Home', '/'], ['Bulk & custom', '/bulk-orders']])],
}, pageHead('Bulk &amp; custom', 'Bandanas for<br>the whole crew.', 'Teams, events, weddings, schools, brands. Tell us how many and when — we’ll come back with a price within a day.', 'Bulk &amp; custom')
  + `<section class="paper"><div class="wrap sec"><div class="cols" style="margin-bottom:56px">
  <div class="box reveal-me"><p class="eyebrow">From 20 pieces</p><h3>Mix our colours</h3><p>Any of the eight colours, in any mix, at a better price per piece than the bundle deal.</p></div>
  <div class="box reveal-me"><p class="eyebrow">Bigger runs</p><h3>Custom colours &amp; prints</h3><p>Your team colours, or your logo in the medallion. Ask us about minimums and timing.</p></div>
  <div class="box reveal-me"><p class="eyebrow">Anywhere</p><h3>Delivered together</h3><p>Shipped in one go across Pakistan or worldwide, packed by person or by box.</p></div>
</div>${contactForm('Bulk or custom', '<div class="row2"><div class="field"><label for="cQty">How many</label><input id="cQty" name="qty" inputmode="numeric" placeholder="e.g. 50"/></div><div class="field"><label for="cWhen">Needed by</label><input id="cWhen" name="when" placeholder="e.g. 20 December"/></div></div>')}</div></section>`, ['assets/forms.js']);

// Utility pages
add('track.html', { url: '/track', index: false, title: 'Track Your Order | Fudgio', desc: 'Track your Fudgio order with your order number and phone number.' },
  pageHead('Track', 'Where’s my bandana?', 'Enter the order number from checkout and the phone number you ordered with.', 'Track your order')
  + `<section class="paper"><div class="wrap sec" style="max-width:860px"><form class="form panel" id="trackForm" novalidate>
    <div class="row2"><div class="field"><label for="tId">Order number</label><input id="tId" placeholder="FUD-1001" autocomplete="off" autocapitalize="characters"/></div>
    <div class="field"><label for="tPhone">Phone number</label><input id="tPhone" type="tel" autocomplete="tel" placeholder="0300 1234567"/></div></div>
    <div class="err" id="tErr" role="alert"></div><button class="btn btn-primary" type="submit">Track order ${ARROW}</button></form>
    <div id="tOut" style="margin-top:28px"></div></div></section>`, ['assets/track.js']);
add('cart.html', { url: '/cart', index: false, title: 'Your Bag | Fudgio', desc: 'The bandanas in your Fudgio bag.' },
  `<section class="paper"><div class="wrap sec"><div class="sec-head"><div class="stack"><p class="eyebrow">Bag</p><h1 class="h2">Your bag</h1></div><p data-ship></p></div><div id="bagRoot"></div></div></section>`, ['assets/cart.js']);
add('checkout.html', { url: '/checkout', index: false, title: 'Checkout | Fudgio', desc: 'Delivery details and payment for your Fudgio order.', bodyClass: 'is-checkout' },
  `<section class="paper"><div class="wrap sec"><div class="sec-head"><div class="stack"><p class="eyebrow">Checkout</p><h1 class="h2">Almost yours.</h1></div><p data-ship></p></div><div class="steps" id="stepsBar"></div><div id="root"></div></div></section>`, ['assets/checkout.js']);
add('404.html', { url: '/404', index: false, title: 'Page not found | Fudgio', desc: 'That page is not here.' },
  `<section class="dark"><div class="wrap lost"><div class="bn">${S.bandanaSVG('#FF2E88', '#FFFFFF')}</div><p class="eyebrow">404</p><h1 class="h1">Lost your<br>bandana?</h1><p class="lede">That page isn’t here. The shop is.</p><a class="btn btn-primary" href="/shop">Shop all colours ${ARROW}</a></div></section>`);

/* ---------------- write ---------------- */
for (const pg of pages) w(pg.file, pg.html);
console.log('wrote', pages.length, 'pages');

// The admin lives on its own subdomain, so it gets its own copy of the print.
w('admin/art.js', r('assets/art.js'));
w('admin/favicon.svg', r('assets/favicon.svg'));

w('robots.txt', `# Fudgio — ${SITE}\nUser-agent: *\nAllow: /\n\nDisallow: /cart\nDisallow: /checkout\nDisallow: /track\nDisallow: /bandana\nDisallow: /api/\nDisallow: /admin/\n\nSitemap: ${SITE}/sitemap.xml\n`);
const today = new Date().toISOString().slice(0, 10);
w('sitemap.xml', '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
  + pages.filter((p) => p.m.index).map((p) => `  <url>\n    <loc>${SITE}${p.m.url}</loc>\n    <lastmod>${today}</lastmod>\n    <priority>${p.m.priority || '0.5'}</priority>\n  </url>\n`).join('')
  + '</urlset>\n');
console.log('wrote robots.txt and sitemap.xml; assets', JSON.stringify(V));
